## Broadcasting in Python

In [1]:
import numpy as np

A is a 3 by 4 matrix:

In [6]:
A = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [7, 8, 9, 10]])
print(A)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 7  8  9 10]]


The columnwise and rowwise sum of A:

In [7]:
colSum = A.sum(axis = 0)
rowSum = A.sum(axis = 1)
print(colSum)
print(rowSum)

[13 16 19 22]
[10 26 34]


More examples:

In [9]:
B = np.array([1, 2, 3, 4])
print(B*100)

[100 200 300 400]


In [11]:
print((100*A/colSum).round(2))

[[ 7.69 12.5  15.79 18.18]
 [38.46 37.5  36.84 36.36]
 [53.85 50.   47.37 45.45]]


Broadcasting a 1 x 3 array into a 2 x 3 one (D is getting broadcasted here):

In [13]:
C = np.array([[1, 2, 3], [4, 5, 6]])
D = np.array([100, 200, 300])
print(C + D)

[[101 202 303]
 [104 205 306]]


In [17]:
print(np.array([[1, 2, 3], [4, 5, 6]]) + np.array([[100], [200]]))

[[101 102 103]
 [204 205 206]]


In [18]:
print(np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]]) + 100)

[[101 102 103]
 [104 105 106]
 [107 108 109]]


### What is Broadcasting
- (m, n) + or - or * or / :
    - (1, n) -> (m, n)
    - (m, 1) -> (m, n)
    - (1, 1) -> (m, n)

In [21]:
X = np.array([[1], [2], [3]])
print(X)
print(X.T)

[[1]
 [2]
 [3]]
[[1 2 3]]
