## Broadcasting in Python and other numpy stuff

In [1]:
import numpy as np

A is a 3 by 4 matrix:

In [6]:
A = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [7, 8, 9, 10]])
print(A)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 7  8  9 10]]


The columnwise and rowwise sum of A:

In [7]:
colSum = A.sum(axis = 0)
rowSum = A.sum(axis = 1)
print(colSum)
print(rowSum)

[13 16 19 22]
[10 26 34]


More examples:

In [9]:
B = np.array([1, 2, 3, 4])
print(B*100)

[100 200 300 400]


In [11]:
print((100*A/colSum).round(2))

[[ 7.69 12.5  15.79 18.18]
 [38.46 37.5  36.84 36.36]
 [53.85 50.   47.37 45.45]]


Broadcasting a 1 x 3 array into a 2 x 3 one (D is getting broadcasted here):

In [13]:
C = np.array([[1, 2, 3], [4, 5, 6]])
D = np.array([100, 200, 300])
print(C + D)

[[101 202 303]
 [104 205 306]]


In [17]:
print(np.array([[1, 2, 3], [4, 5, 6]]) + np.array([[100], [200]]))

[[101 102 103]
 [204 205 206]]


In [18]:
print(np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]]) + 100)

[[101 102 103]
 [104 105 106]
 [107 108 109]]


### What is Broadcasting
- (m, n) + or - or * or / :
    - (1, n) -> (m, n)
    - (m, 1) -> (m, n)
    - (1, 1) -> (m, n)

In [21]:
X = np.array([[1], [2], [3]])
print(X)
print(X.T)

[[1]
 [2]
 [3]]
[[1 2 3]]


## random

In [22]:
a = np.random.randn(5) # this is a rank 1 vector (don't use it, it's wierd)
b = np.random.randn(5, 1) # this is a 5 by 1 vector (use it, it's friendly)
print(a, a.T)
print(b, b.T)

[-0.5337121  -0.94848289  0.36806707 -0.87712686  0.26099123] [-0.5337121  -0.94848289  0.36806707 -0.87712686  0.26099123]
[[-0.93702753]
 [-0.42430956]
 [ 2.17368218]
 [ 0.44044727]
 [-0.10633354]] [[-0.93702753 -0.42430956  2.17368218  0.44044727 -0.10633354]]


# assertion and reshape

- assert: this is an inexpensive function which will halt the program if the given condition is false (throw an assertion error) it is usefull for debugging and making sure that some things are how we want them (for eg, there are no rank 1 vectors)
- reshape: this will reshape the rank 1 array, a to a column vector

In [32]:
#assert(a.shape == (5, 1))
assert(b.shape == (5, 1))
a.reshape((5, 1))

array([[-0.5337121 ],
       [-0.94848289],
       [ 0.36806707],
       [-0.87712686],
       [ 0.26099123]])